/***************************************************************************
  attribute_copy.cpp
  copy field from another layer to current layer.
  -------------------
         begin                : [PluginDate]
         copyright            : [(C) Your Name and Date]
         email                : [Your Email]

 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

//
// QGIS Specific includes
//

#include <qgisinterface.h>
#include <qgisgui.h>

#include "attribute_copy.h"
#include "attributecopy.h"
#include "qgisplugin.h"
//
// Qt4 Related Includes
//

#include <QAction>
#include <QToolBar>
#include <qmessagebox.h>

static const QString sName = QObject::tr( "attribute copy" );
static const QString sDescription = QObject::tr( "copy field from another layer to current layer." );
static const QString sCategory = QObject::tr( "Silen" );
static const QString sPluginVersion = QObject::tr( "Version 0.1" );
static const QgisPlugin::PLUGINTYPE sPluginType = QgisPlugin::UI;
static const QString sPluginIcon = ":/new/prefix1/Resources/ContentsWindowDrapedLayers32.png";

//////////////////////////////////////////////////////////////////////
//
// THE FOLLOWING METHODS ARE MANDATORY FOR ALL PLUGINS
//
//////////////////////////////////////////////////////////////////////

/**
 * Constructor for the plugin. The plugin is passed a pointer
 * an interface object that provides access to exposed functions in QGIS.
 * @param theQGisInterface - Pointer to the QGIS interface object
 */
attribute_copy::attribute_copy( QgisInterface * theQgisInterface ):
    QgisPlugin( sName, sDescription, sCategory, sPluginVersion, sPluginType ),
    mQGisIface( theQgisInterface )
	,mQActionPointer(nullptr)
	,myPlugin(nullptr)
{
	
}
attribute_copy::~attribute_copy()
{
	
}

/*
 * Initialize the GUI interface for the plugin - this is only called once when the plugin is
 * added to the plugin registry in the QGIS application.
 */
void attribute_copy::initGui()
{

  // Create the action for tool
  mQActionPointer = new QAction( QIcon( ":/new/prefix1/Resources/ContentsWindowDrapedLayers32.png" ), tr( "attribute copy" ), this );
  mQActionPointer->setObjectName( "mQSilenPluginTest" );//这里改了ObjectName名称后就可以在qgis toolrbar里显示图标，为什么？
  // Set the what's this text
  mQActionPointer->setWhatsThis( tr( "Replace this with a short description of what the plugin does" ) );
  // Connect the action to the run
  connect( mQActionPointer, SIGNAL( triggered() ), this, SLOT( run() ) );
  // Add the icon to the toolbar
 // mQGisIface->addToolBarIcon( mQActionPointer );
//  mQGisIface->addPluginToMenu( tr( "&attribute copy" ), mQActionPointer );
  mQGisIface->addDatabaseToolBarIcon(mQActionPointer);

}
//method defined in interface
void attribute_copy::help()
{
  //implement me!
}

// Slot called when the menu item is triggered
// If you created more menu items / toolbar buttons in initiGui, you should
// create a separate handler for each action - this single run() method will
// not be enough
void attribute_copy::run()
{
 /* attribute_copyGui *myPluginGui = new attribute_copyGui( mQGisIface->mainWindow(), QgisGui::ModalDialogFlags );
  myPluginGui->setAttribute( Qt::WA_DeleteOnClose );

  myPluginGui->show();*/

  myPlugin=new attributecopy(mQGisIface->mainWindow());
  //myPlugin->setAttribute(Qt::WA_DeleteOnClose);
  myPlugin->show();

}

// Unload the plugin by cleaning up the GUI
void attribute_copy::unload()
{
  // remove the GUI
  mQGisIface->removePluginMenu( "&attribute copy", mQActionPointer );
  mQGisIface->removeToolBarIcon( mQActionPointer );
  delete mQActionPointer;
}


//////////////////////////////////////////////////////////////////////////
//
//
//  THE FOLLOWING CODE IS AUTOGENERATED BY THE PLUGIN BUILDER SCRIPT
//    YOU WOULD NORMALLY NOT NEED TO MODIFY THIS, AND YOUR PLUGIN
//      MAY NOT WORK PROPERLY IF YOU MODIFY THIS INCORRECTLY
//
//
//////////////////////////////////////////////////////////////////////////


/**
 * Required extern functions needed  for every plugin
 * These functions can be called prior to creating an instance
 * of the plugin class
 */
// Class factory to return a new instance of the plugin class
QGISEXTERN QgisPlugin * classFactory( QgisInterface * theQgisInterfacePointer )
{
  return new attribute_copy( theQgisInterfacePointer );
}
// Return the name of the plugin - note that we do not user class members as
// the class may not yet be insantiated when this method is called.
QGISEXTERN QString name()
{
  return sName;
}

// Return the description
QGISEXTERN QString description()
{
  return sDescription;
}

// Return the category
QGISEXTERN QString category()
{
  return sCategory;
}

// Return the type (either UI or MapLayer plugin)
QGISEXTERN int type()
{
  return sPluginType;
}

// Return the version number for the plugin
QGISEXTERN QString version()
{
  return sPluginVersion;
}

QGISEXTERN QString icon()
{
  return sPluginIcon;
}

// Delete ourself
QGISEXTERN void unload( QgisPlugin * thePluginPointer )
{
  delete thePluginPointer;
}